name: nodejs app build
on:
  push:
    branches:
    - master
jobs:
  lint-job1:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the Repo
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Review of code
      run: npm run lint
  test-job2:
    runs-on: ubuntu-latest
    steps:
    - name: Clone the Repo
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Test code
      run: npm run test
    - name: Upload test report on github
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: test2.json
  build-job3:
    needs: test-job2
    runs-on: ubuntu-latest
    steps:
    - name: Clone the Repo
      uses: actions/checkout@v4
    - name: Install dependencies
      run: npm ci
    - name: Build Code
      run: npm run build
